export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR = 'DATABASE_QUERY_ERROR',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  INVALID_INPUT = 'INVALID_INPUT',
  CONFLICT_DETECTED = 'CONFLICT_DETECTED',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
